# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-06-26 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='\u5934\u50cf')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='\u63cf\u8ff0')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': '\u8bb2\u5e08',
                'verbose_name_plural': '\u8bb2\u5e08',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='cover_url',
            field=models.URLField(blank=True, null=True, verbose_name='\u5c01\u9762'),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, default=0, editable=False, help_text='\u5355\u4f4d: \u79d2.', verbose_name='\u65f6\u957f'),
        ),
        migrations.AddField(
            model_name='video',
            name='size',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, help_text='\u5355\u4f4d: \u6bd4\u7279Byte', verbose_name='\u5927\u5c0f'),
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '\u8f6c\u7801\u4e2d'), (2, '\u5b8c\u6210'), (0, '\u5931\u8d25')], default=1, verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='video',
            name='owner_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='\u5c5e\u4e3b\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='video',
            name='owner_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name='\u5f52\u7c7b'),
        ),
        migrations.AddField(
            model_name='video',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='media.Lecturer', verbose_name='\u8bb2\u5e08'),
        ),
    ]
