# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-07-16 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20200626_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
    ]
