# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2023-08-30 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='\u6807\u7b7e'),
        ),
    ]
